<?php

return [
    'log_patterns' => [
        'formatlog:sendmail' => 'processSendMail',
        'formatlog:rolelogin' => 'processRoleLogin',
        'formatlog:rolelogout' => 'processRoleLogout',
        'formatlog:trade' => 'processTrade',
        'formatlog:task' => 'processTask',
        '丢弃包裹' => 'processDropItem',
        '丢弃装备' => 'processDropEquipment',
        '拣起金钱' => 'processPickupMoney',
        '丢弃金钱' => 'processDiscardMoney',
        '从NPC购买了' => 'processBuyItem',
        '卖店' => 'processSellItem',
        '得到金钱' => 'processGetMoney',
        '拣起' => 'processPickupItem',
        '在百宝阁购买' => 'processPurchaseFromAuction',
    ],
    'messages' => [
        'roleLogout' => 'Role ID %d from user %d logged out',
        'roleLogin' => 'Role ID %d from user %d logged in',
        'dropItem' => 'User %d discarded %d of item %d',
        'pickupMoney' => 'Role %s picked up %d money',
        'discardMoney' => 'User %d discarded %d money',
        'buyItem' => 'User %d bought %d of item %d from NPC',
        'sellItem' => 'User %d sold %d of item %d',
        'getMoney' => 'User %d received %d money',
        'trade' => 'Role %d traded with role %d. Money exchanged: %d from role %d and %d from role %d. Role %d traded %s items. And Role %d traded %s items.',
        'dropEquipment' => 'User %d discarded equipment %d',
        'pickupItem' => 'User %d picked up %d of item %d (discarded by user %d)',
        'purchaseFromAuction' => 'User %d purchased %d items from the auction house, spent %d points, remaining balance: %d points',
        'processStartTask' => 'Role ID %d started task with task ID %d (type %d)',
        'processGiveUpTask' => 'Role ID %d gave up task with task ID %d (type %d)',
        'receiveItemFromTask' => 'Role ID %d received item with item ID %d (count %d) from task with task ID %d (type %d)',
        'deliverByAwardData' => 'Role ID %d completed task with task ID %d (type %d), success = %d, gold = %d, exp = %d, sp = %d, reputation = %d',
    ],
];
